name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: npm audit
        run: npm audit --audit-level=high

  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - name: check format and types
        run: make check

  playwright:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    env:
      PUBLIC_HIGHLIGHTS_API_URL: ${{ vars.PUBLIC_HIGHLIGHTS_API_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - name: install browsers
        run: npx playwright install --with-deps
      # Required to build the project for Playwright tests
      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: run tests
        run: npm run playwright
      - uses: actions/upload-artifact@v5
        if: ${{ failure() }}
        with:
          name: test-artifacts
          path: |
            test/browser/artifacts/
            !test/browser/artifacts/.last-run.json
            test/browser/report/
          retention-days: 1

  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - name: run tests
        run: npm run vitest
