name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: npm audit
        run: npm audit

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - name: prettier
        run: npm run format

  playwright:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    env:
      PUBLIC_HIGHLIGHTS_API_URL: ${{ vars.PUBLIC_HIGHLIGHTS_API_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - name: install browsers
        run: npx playwright install --with-deps
      # Required to build the project for Playwright tests
      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: run tests
        run: make test
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name:
          path: |
            test/artifacts/
            !test/artifacts/.last-run.json
            test/report/
          retention-days: 1
